### ISSUE TITLE
segfault after welcome dialog

### ISSUE THREAD

**Issue by xraw** [soramimi/Guitar#74]
1. Launch Guitar
2. Confirm first selected Language (English) with 'Enter'
3. Enter /usr/bin/git for git, Enter /usr/bin/file for file, confirm with 'Enter'
4. Accept user + mail from ~/.gitconfig and confirm with 'Enter'
5. Enter path to a git project, like ~/src/mywork and confirm with 'Enter'
6. Confirm summary with 'Enter'

After short analysis, the call in BasicMainWindow.cpp:1892, g is null and call to g->setUser(...) crashes.

Backtrace:

Thread 1 "Guitar" received signal SIGSEGV, Segmentation fault.
0x00000000005d65ea in Git::gitCommand (this=0x0) at /home/wg/src/Guitar/src/Git.cpp:117
117             Q_ASSERT(m);
(gdb)
(gdb)
(gdb) bt
#0  0x00000000005d65ea in Git::gitCommand (this=0x0) at /home/wg/src/Guitar/src/Git.cpp:117
#1  0x00000000005d6b78 in Git::git (this=0x0, arg=..., chdir=false, errout=false, pty=0x0) at /home/wg/src/Guitar/src/Git.cpp:154
#2  0x00000000005dcf51 in Git::setUser (this=0x0, user=..., global=true) at /home/wg/src/Guitar/src/Git.cpp:1096
#3  0x0000000000571811 in BasicMainWindow::execWelcomeWizardDialog (this=0x7fffffffdec0) at /home/wg/src/Guitar/src/BasicMainWindow.cpp:1892
#4  0x0000000000607f31 in MainWindow::onStartEvent (this=0x7fffffffdec0) at /home/wg/src/Guitar/src/MainWindow.cpp:242
#5  0x0000000000608982 in MainWindow::customEvent (this=0x7fffffffdec0, e=0x9d1270) at /home/wg/src/Guitar/src/MainWindow.cpp:430
#6  0x00007ffff6e8513d in QObject::event(QEvent*) () from /usr/lib64/libQt5Core.so.5
#7  0x00007ffff78af150 in QWidget::event(QEvent*) () from /usr/lib64/libQt5Widgets.so.5
#8  0x00007ffff79ba414 in QMainWindow::event(QEvent*) () from /usr/lib64/libQt5Widgets.so.5
#9  0x0000000000568258 in BasicMainWindow::event (this=0x7fffffffdec0, event=0x9d1270) at /home/wg/src/Guitar/src/BasicMainWindow.cpp:190
#10 0x000000000060894b in MainWindow::event (this=0x7fffffffdec0, event=0x9d1270) at /home/wg/src/Guitar/src/MainWindow.cpp:424
#11 0x00007ffff786f5f2 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib64/libQt5Widgets.so.5
#12 0x00007ffff78786a0 in QApplication::notify(QObject*, QEvent*) () from /usr/lib64/libQt5Widgets.so.5
#13 0x00007ffff6e5ac62 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib64/libQt5Core.so.5
#14 0x00007ffff6e5d768 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/lib64/libQt5Core.so.5
#15 0x00007ffff6eaece3 in ?? () from /usr/lib64/libQt5Core.so.5
#16 0x00007ffff3e7222d in g_main_context_dispatch () from /usr/lib64/libglib-2.0.so.0
#17 0x00007ffff3e72480 in ?? () from /usr/lib64/libglib-2.0.so.0
#18 0x00007ffff3e7250f in g_main_context_iteration () from /usr/lib64/libglib-2.0.so.0
#19 0x00007ffff6eae381 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQt5Core.so.5
#20 0x00007ffff6e5992b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib64/libQt5Core.so.5
#21 0x00007ffff6e610fe in QCoreApplication::exec() () from /usr/lib64/libQt5Core.so.5
#22 0x000000000055344e in main (argc=1, argv=0x7fffffffe2c8) at /home/wg/src/Guitar/src/main.cpp:180

**Comment by Symbian9** [comment]
> Launch Guitar

Add Guitar version number/commit info.

**Comment by xraw** [comment]
GNU/Linux (Slackware 14.2, Kernel 5.4.28), Guitar built from master branch (b17228061f81ed00eb1a11e8040e3da0134be2c9)

**Comment by Symbian9** [comment]
> Guitar built from master branch

So, you built it yourself.

Could you test latest AppImage build too?

- https://github.com/soramimi/Guitar/releases/tag/continuous

**Comment by xraw** [comment]
Build manually exactly, but left all build settings as they were.

AppImage -> following sequence as stated at the top -> crash unfortunately.
I will dig deeper and provide info on this, after I have tested this on another system/distribution.

```
Thread 1 "AppRun" received signal SIGSEGV, Segmentation fault.
0x00000000004825d0 in ?? ()
(gdb) bt
#0  0x00000000004825d0 in ?? ()
#1  0x0000000000483a7f in ?? ()
#2  0x0000000000487e10 in ?? ()
#3  0x000000000043f9ce in ?? ()
#4  0x00000000004b2568 in ?? ()
#5  0x00007ffff6a9dfb5 in QObject::event(QEvent*) ()
   from /tmp/.mount_Guitar4WtgAz/usr/bin/../lib/libQt5Core.so.5
#6  0x00007ffff746e5d3 in QWidget::event(QEvent*) ()
   from /tmp/.mount_Guitar4WtgAz/usr/bin/../lib/libQt5Widgets.so.5
#7  0x00007ffff757c52b in QMainWindow::event(QEvent*) ()
   from /tmp/.mount_Guitar4WtgAz/usr/bin/../lib/libQt5Widgets.so.5
#8  0x00007ffff74328fc in QApplicationPrivate::notify_helper(QObject*, QEvent*)
    () from /tmp/.mount_Guitar4WtgAz/usr/bin/../lib/libQt5Widgets.so.5
#9  0x00007ffff74399e0 in QApplication::notify(QObject*, QEvent*) ()
   from /tmp/.mount_Guitar4WtgAz/usr/bin/../lib/libQt5Widgets.so.5
#10 0x00007ffff6a72fb5 in QCoreApplication::notifyInternal2(QObject*, QEvent*)
    () from /tmp/.mount_Guitar4WtgAz/usr/bin/../lib/libQt5Core.so.5
#11 0x00007ffff6a75593 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) ()
   from /tmp/.mount_Guitar4WtgAz/usr/bin/../lib/libQt5Core.so.5
#12 0x00007ffff6ac4c33 in ?? ()
   from /tmp/.mount_Guitar4WtgAz/usr/bin/../lib/libQt5Core.so.5
#13 0x00007ffff54d522d in g_main_context_dispatch ()
   from /usr/lib64/libglib-2.0.so.0
#14 0x00007ffff54d5480 in ?? () from /usr/lib64/libglib-2.0.so.0
#15 0x00007ffff54d550f in g_main_context_iteration ()
   from /usr/lib64/libglib-2.0.so.0
#16 0x00007ffff6ac445c in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /tmp/.mount_Guitar4WtgAz/usr/bin/../lib/libQt5Core.so.5
#17 0x00007ffff6a7111b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /tmp/.mount_Guitar4WtgAz/usr/bin/../lib/libQt5Core.so.5
#18 0x00007ffff6a798a4 in QCoreApplication::exec() ()
   from /tmp/.mount_Guitar4WtgAz/usr/bin/../lib/libQt5Core.so.5
#19 0x000000000042828d in ?? ()
#20 0x00007ffff628be5b in __libc_start_main () from /lib64/libc.so.6
#21 0x0000000000428b40 in ?? ()
```
